name = "trashttpandas"
main = "./index.ts"
compatibility_date = "2023-08-03"

kv_namespaces = [
  { binding = "CODES_KV", id = "6d813d9939be47a98daf2e8fc3abe5f0", preview_id = "6d813d9939be47a98daf2e8fc3abe5f0" },
]
