name = "trashttpandas"
type = "webpack"

account_id = "1691cf1451d1a8339e42de4c99264659"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-30"

kv_namespaces = [ 
  { binding = "CODES", id = "6d813d9939be47a98daf2e8fc3abe5f0" }
]